### ISSUE TITLE
Configure CI for core repos

### ISSUE THREAD

**Issue by janeeisenstein** [simplworld/simpl.world.website#72]
We need CI tasks to ensure code going into the core master branches passes unit tests.

Use Travis CI ~~with tox~~

For example configurations see:
https://github.com/revsys/django-test-plus/blob/master/.travis.yml
https://github.com/revsys/django-test-plus/blob/master/tox.ini

Subtasks:

- [x] simplworld/simpl-users#3
- [x] simplworld/simpl-client#1
- [x] simplworld/simpl-react#7
- [x] simplworld/simpl-games-api#6

TODO:
- Use tox to test against >1 python and >postgresql version.
- Add CI to simpl-modelservice once it's installable.
